/opt/uncut/data/logs/nginx/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0640 root root
    sharedscripts
    postrotate
        [ -f /run/nginx/nginx.pid ] && kill -USR1 `cat /run/nginx/nginx.pid` || true
    endscript
}
