[Definition]
failregex = ^<HOST> -.*"(GET|POST|HEAD) \/(wp-admin|wp-login|\.env|phpmyadmin|admin|actuator|api\/v1\/pods).* HTTP.*" 40[34]
^<HOST> -.*"(GET|POST|HEAD) \/.*dns-query.* HTTP.*" 40[34]
ignoreregex =
